Vagrant.configure("2") do |config|
if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false 
end
config.vm.define :servidor do |servidor|
servidor.vm.box = "centos/stream8"
servidor.vm.network :private_network, ip: "192.168.50.5"
servidor.vm.hostname = "servidor"
servidor.vm.network :forwarded_port, guest: 443, host: 5568
end
end
